/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ForwarderFactoryInterface extends Interface {
    getFunction(nameOrSignature: "batchFlushTokens" | "centralWallet" | "createForwarder" | "forwarderToUser" | "implementation" | "owner" | "predictForwarderAddress" | "renounceOwnership" | "transferOwnership" | "updateCentralWallet" | "userForwarders"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchFlushed" | "ForwarderCreated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'batchFlushTokens', values: [AddressLike[], AddressLike]): string;
encodeFunctionData(functionFragment: 'centralWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'createForwarder', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'forwarderToUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'implementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictForwarderAddress', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateCentralWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userForwarders', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'batchFlushTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'centralWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'forwarderToUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'implementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictForwarderAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCentralWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userForwarders', data: BytesLike): Result;
  }

  
    export namespace BatchFlushedEvent {
      export type InputTuple = [forwarders: AddressLike[], token: AddressLike];
      export type OutputTuple = [forwarders: string[], token: string];
      export interface OutputObject {forwarders: string[], token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ForwarderCreatedEvent {
      export type InputTuple = [userId: BytesLike, forwarderAddress: AddressLike];
      export type OutputTuple = [userId: string, forwarderAddress: string];
      export interface OutputObject {userId: string, forwarderAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ForwarderFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ForwarderFactory;
    waitForDeployment(): Promise<this>;

    interface: ForwarderFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batchFlushTokens: TypedContractMethod<
      [forwarders: AddressLike[], tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    centralWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createForwarder: TypedContractMethod<
      [userId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    forwarderToUser: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    implementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictForwarderAddress: TypedContractMethod<
      [userId: BytesLike, ],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCentralWallet: TypedContractMethod<
      [newWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userForwarders: TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batchFlushTokens'): TypedContractMethod<
      [forwarders: AddressLike[], tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'centralWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createForwarder'): TypedContractMethod<
      [userId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'forwarderToUser'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'implementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictForwarderAddress'): TypedContractMethod<
      [userId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCentralWallet'): TypedContractMethod<
      [newWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userForwarders'): TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'BatchFlushed'): TypedContractEvent<BatchFlushedEvent.InputTuple, BatchFlushedEvent.OutputTuple, BatchFlushedEvent.OutputObject>;
getEvent(key: 'ForwarderCreated'): TypedContractEvent<ForwarderCreatedEvent.InputTuple, ForwarderCreatedEvent.OutputTuple, ForwarderCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'BatchFlushed(address[],address)': TypedContractEvent<BatchFlushedEvent.InputTuple, BatchFlushedEvent.OutputTuple, BatchFlushedEvent.OutputObject>;
      BatchFlushed: TypedContractEvent<BatchFlushedEvent.InputTuple, BatchFlushedEvent.OutputTuple, BatchFlushedEvent.OutputObject>;
    

      'ForwarderCreated(bytes32,address)': TypedContractEvent<ForwarderCreatedEvent.InputTuple, ForwarderCreatedEvent.OutputTuple, ForwarderCreatedEvent.OutputObject>;
      ForwarderCreated: TypedContractEvent<ForwarderCreatedEvent.InputTuple, ForwarderCreatedEvent.OutputTuple, ForwarderCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }