/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IForwarderInterface extends Interface {
    getFunction(nameOrSignature: "flushETH" | "flushToken" | "initialize"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'flushETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'flushToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'flushETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flushToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  }

  

  export interface IForwarder extends BaseContract {
    
    connect(runner?: ContractRunner | null): IForwarder;
    waitForDeployment(): Promise<this>;

    interface: IForwarderInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    flushETH: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    flushToken: TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initialize: TypedContractMethod<
      [_centralWallet: AddressLike, _factory: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'flushETH'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flushToken'): TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_centralWallet: AddressLike, _factory: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }