/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ForwarderFactory } from './ForwarderFactory.js';
export type { IForwarder } from './IForwarder.js';