/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ForwarderImplementationInterface extends Interface {
    getFunction(nameOrSignature: "centralWallet" | "factory" | "flushETH" | "flushToken" | "initialize" | "initialized"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ETHForwarded" | "TokensForwarded"): EventFragment;

    encodeFunctionData(functionFragment: 'centralWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'flushETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'flushToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initialized', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'centralWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flushETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flushToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialized', data: BytesLike): Result;
  }

  
    export namespace ETHForwardedEvent {
      export type InputTuple = [amount: BigNumberish, to: AddressLike];
      export type OutputTuple = [amount: bigint, to: string];
      export interface OutputObject {amount: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensForwardedEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish, to: AddressLike];
      export type OutputTuple = [token: string, amount: bigint, to: string];
      export interface OutputObject {token: string, amount: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ForwarderImplementation extends BaseContract {
    
    connect(runner?: ContractRunner | null): ForwarderImplementation;
    waitForDeployment(): Promise<this>;

    interface: ForwarderImplementationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    centralWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    flushETH: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    flushToken: TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initialize: TypedContractMethod<
      [_centralWallet: AddressLike, _factory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initialized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'centralWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'flushETH'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flushToken'): TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_centralWallet: AddressLike, _factory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'ETHForwarded'): TypedContractEvent<ETHForwardedEvent.InputTuple, ETHForwardedEvent.OutputTuple, ETHForwardedEvent.OutputObject>;
getEvent(key: 'TokensForwarded'): TypedContractEvent<TokensForwardedEvent.InputTuple, TokensForwardedEvent.OutputTuple, TokensForwardedEvent.OutputObject>;

    filters: {
      
      'ETHForwarded(uint256,address)': TypedContractEvent<ETHForwardedEvent.InputTuple, ETHForwardedEvent.OutputTuple, ETHForwardedEvent.OutputObject>;
      ETHForwarded: TypedContractEvent<ETHForwardedEvent.InputTuple, ETHForwardedEvent.OutputTuple, ETHForwardedEvent.OutputObject>;
    

      'TokensForwarded(address,uint256,address)': TypedContractEvent<TokensForwardedEvent.InputTuple, TokensForwardedEvent.OutputTuple, TokensForwardedEvent.OutputObject>;
      TokensForwarded: TypedContractEvent<TokensForwardedEvent.InputTuple, TokensForwardedEvent.OutputTuple, TokensForwardedEvent.OutputObject>;
    
    };
  }