/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ForwarderImplementation } from './ForwarderImplementation.js';
export type { IERC20 } from './IERC20.js';