/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IForwarder, IForwarderInterface } from "../../ForwarderFactory.sol/IForwarder.js";

  const _abi = [
  {
    "inputs": [],
    "name": "flushETH",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      }
    ],
    "name": "flushToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_centralWallet",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_factory",
        "type": "address"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IForwarder__factory {
    static readonly abi = _abi;
    static createInterface(): IForwarderInterface {
      return new Interface(_abi) as IForwarderInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IForwarder {
      return new Contract(address, _abi, runner) as unknown as IForwarder;
    }
  }
  