/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ForwarderImplementation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ForwarderImplementation__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'ForwarderFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ForwarderFactory__factory>
getContractFactory(name: 'IForwarder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IForwarder__factory>

  getContractAt(name: 'ForwarderImplementation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ForwarderImplementation>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'ForwarderFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ForwarderFactory>
getContractAt(name: 'IForwarder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IForwarder>

  deployContract(name: 'ForwarderImplementation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ForwarderImplementation>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'ForwarderFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ForwarderFactory>
deployContract(name: 'IForwarder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IForwarder>

  deployContract(name: 'ForwarderImplementation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ForwarderImplementation>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'ForwarderFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ForwarderFactory>
deployContract(name: 'IForwarder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IForwarder>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  